config/routes.rb
Rails.application.routes.draw do

  root to: 'visitors#index'

  # explicitly set routing for none typical controller actions
  get  'admin', :to => 'access#menu'
  get  'access/menu'
  get  'access/login'
  post 'access/attempt_login'
  get  'access/logout'

  # gives all 8 actions on users
  resources :users do
    member do
      get :delete
    end
  end

  # gives all 8 actions on roles
  resources :roles do
    member do
      get :delete
    end
  end

  # gives all 8 actions on events
  resources :events do
    member do
      get :delete
    end
  end


end

app/models/user.rb
class User < ApplicationRecord

  #use bcrypt to secure our password
  has_secure_password

  #role relational mapping
  has_and_belongs_to_many :roles

  #add constraints to obj ect properties to protect against zee bad guys
  validates :password, length:{minimum:6}, on: :create

  EMAIL_REGEX = /\A[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}\Z/i

  validates :first_name,  :presence => true,
            :length => { :maximum => 25 }

  validates :last_name, :presence => true,
            :length => { :maximum => 50 }

  validates :username, :length => { :within => 1..25 },
            :uniqueness => true

  validates :email, :presence => true,
            :length => { :maximum => 100 },
            :format => EMAIL_REGEX,
            :confirmation => true

  validates :password, length:{minimum:6}, on: :create

  # db query manipulations go here!
  scope :sorted, lambda { order("last_name desc")}
  scope :active, lambda { where(:deleted => nil)}

  # custom method
  def name
    "#{first_name} #{last_name}"
  end

  def is_admin
    admin = Role.find_by_name('Admin')
    admin ? has_role(admin.name) : false
  end

  def has_role(role)
    roles.any?{|a| a.name == role}
  end

  # custom validation
  private

  def username_is_allowed
    if FORBIDDEN_USERNAMES.include?(username)
      errors.add(:username, "has been restricted from use.")
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :confirm_logged_in

  def index
    @users = User.sorted.active
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      flash[:notice] = "congratulations, its a new user!"
      redirect_to(users_path)
    else
      render('new')
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      flash[:warning] = 'User updated'
      redirect_to(users_path)
    else
      flash.now[:warning] = "Error updating user"
      render('edit')
    end
  end

  def delete
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.deleted = true

    if @user.save
      flash[:notice] = "Admin User Destroyed!"
      redirect_to(users_path)
    else
      flash[:notice] = "Failed to destroy the user"
      render('delete')
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :username, :password, :role_ids => [])
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= error_messages_for(f.object) %>

<div class="form-group row">
  <%= f.label :first_name, class: 'col-xs-2 col-form-label'  %>
  <div class="col-xs-10">
    <%= f.text_field :first_name, class: 'form-control' %>
  </div>
</div>
<div class="form-group row">
  <%= f.label :last_name, class: 'col-xs-2 col-form-label'  %>
  <div class="col-xs-10">
    <%= f.text_field :last_name, class: 'form-control' %>
  </div>
</div>
<div class="form-group row">
  <%= f.label :email, class: 'col-xs-2 col-form-label'  %>
  <div class="col-xs-10">
    <%= f.text_field :email, class: 'form-control' %>
  </div>
</div>
<div class="form-group row">
  <%= f.label :username, class: 'col-xs-2 col-form-label'  %>
  <div class="col-xs-10">
    <%= f.text_field :username, class: 'form-control' %>
  </div>
</div>
<div class="form-group row">
  <%= f.label :password, class: 'col-xs-2 col-form-label'  %>
  <div class="col-xs-10">
    <%= f.password_field :password, class: 'form-control' %>
  </div>
</div>

<div class="form-group row">
  <label class="col-xs-2 col-form-label">Roles</label>
  <div class="col-xs-10 checkbox-list">
    <%= f.collection_check_boxes(:role_ids, Role.all, :id, :name )  -%>
  </div>
</div>

app/views/users/delete.html.erb
<% @page_title = "Delete Admin User" %>

<%= link_to(" << Back to List", delete_user_path, :class => 'back-link') %>

<div class="user delete">
  <h2>Delete Users</h2>

  <%= form_for(@user, :method => 'delete') do  |f| %>

      <p>Are you sure you want to permanently delete this User?</p>

      <p class="reference-name"><%= f.object.first_name %> <%= f.object.last_name %></p>

      <div class="form-buttons">
        <%= f.submit("Delete User") %>
      </div>

  <% end %>
</div>

app/views/users/edit.html.erb
<% @page_title = "Edit User" %>

<%= link_to("<< Back to List", users_path, :class => 'back-link') %>

<div class="users edit">
  <h2>Update User</h2>

  <%= form_for(@user) do |f| %>

      <%= render(:partial => 'form', :locals => {:f => f}) %>

      <div class="form-buttons">
        <%= f.submit("Update User", class: 'btn btn-primary') %>
      </div>
  <% end %>
</div>

app/views/users/index.html.erb
<% @page_title = "Admin Users" %>

<div class="users index">
  <h2>Users</h2>

  <div><%= pluralize(@users.size, 'user') %> found</div>

  <%= link_to("add new user", new_user_path, :class => 'action new') %>
  <hr />
  <table class="table" summary="Admin User list" id="table_users">
    <thead>
      <tr class="header">
        <th>id</th>
        <th>name</th>
        <th>email</th>
        <th>username</th>
        <th>created at</th>
        <th>roles</th>

        <th>action</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
          <tr>
            <td><%= user.id %></td>
            <td><%= user.name %></td>
            <td><%= mail_to(user.email) %></td>
            <td><%= user.username %></td>
            <td><%= user.created_at.to_s(:long) %></td>
            <td>
              <% user.roles.each do |role| %>
                <div><%= role.name %></div>
              <% end %>
            </td>

            <td class="actions">
              <%= link_to("Show", user_path(:id => user.id), :class => 'action show') %>
              <%= link_to("Edit", edit_user_path(:id => user.id), :class => 'action edit') %>
              <%= link_to("Delete", delete_user_path(:id => user.id), :class => 'action delete') %>
            </td>
          </tr>
      <% end %>
    </tbody>
  </table>
</div>
<script>
  $(document).ready(function() {
    $('#table_users').DataTable();
  } );
</script>

app/views/users/new.html.erb
<%= link_to("<< Back to List", users_path, :class => 'back-link') %>
<div class="pages new">
  <h2>Users</h2>

  <%= form_for(@user, :url => users_path, :method => 'post') do |f| %>
      <%= render(:partial => 'form', :locals => {:f => f}) %>


      <%= f.submit "Create User", class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>