config/routes.rb
Rails.application.routes.draw do

  root to: 'visitors#index'

  # explicitly set routing for none typical controller actions
  get  'admin', :to => 'access#menu'
  get  'access/menu'
  get  'access/login'
  post 'access/attempt_login'
  get  'access/logout'

  # gives all 8 actions on users
  resources :users do
    member do
      get :delete
    end
  end

  # gives all 8 actions on roles
  resources :roles do
    member do
      get :delete
    end
  end

  # gives all 8 actions on events
  resources :events do
    member do
      get :delete
    end
  end


end

app/controllers/access_controller.rb
class AccessController < ApplicationController

  before_action :confirm_logged_in, :except => [:login, :attempt_login, :logout]

  before_action :admin_only, :only => [:menu]

  def menu
    # displat text & links
    @is_admin = is_admin
    @username = session[:username]
  end

  def login
    # login form
  end

  def attempt_login

    if params[:username].present? && params[:password_digest].present?
      found_user = User.where(:username => params[:username]).first
      if found_user
        authorized_user = found_user.authenticate(params[:password_digest])
      end
    end

    if authorized_user
      session[:user_id]   = authorized_user.id
      session[:username]  = authorized_user.username
      flash[:notice]      = "you are now logged in."
      authorized_user.is_admin ? redirect_to(admin_path) : redirect_to('/')

    else
      flash.now[:notice] = "Invalid username/password combination."
      render('login')
    end
  end

  def logout
    session[:user_id]   = nil
    session[:username]  = nil
    flash[:notice]      = 'logged out'
    redirect_to('/')
  end

end

app/helpers/access_helper.rb
module AccessHelper
end

app/views/access/login.html.erb
<% @page_title = "Admin Login" %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <%= form_tag(access_attempt_login_path, :method => :post) do %>
    <%= label_tag(:username) %>
    <%= text_field_tag(:username, params[:username], class:'form-control') %>
    <br />
    <%= label_tag(:password_digest) %></td>
    <%= password_field_tag(:password_digest, '', class: 'form-control') %>
    <br />
    <%= submit_tag("Log In", class: "btn btn-primary") %>
  <% end %>
  </div>
</div>

app/views/access/menu.html.erb
<% @page_title = "Admin Menu" %>

<div class="menu">
  <h2>Admin Menu.</h2>
  <div class="identity">Logged in as: <%= @username %></div>
  <ul>
    <li><%= link_to 'Users', users_path, class: 'nav-link' %></li>
    <li><%= link_to 'Roles', roles_path, class: 'nav-link' %></li>
    <li><%= link_to 'Events', events_path, class: 'nav-link' %></li>
  </ul>
</div>