config/routes.rb
Rails.application.routes.draw do

  root to: 'visitors#index'

  # explicitly set routing for none typical controller actions
  get  'admin', :to => 'access#menu'
  get  'access/menu'
  get  'access/login'
  post 'access/attempt_login'
  get  'access/logout'

  # gives all 8 actions on users
  resources :users do
    member do
      get :delete
    end
  end

  # gives all 8 actions on roles
  resources :roles do
    member do
      get :delete
    end
  end

  # gives all 8 actions on events
  resources :events do
    member do
      get :delete
    end
  end


end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :distance
end

app/models/event_type.rb
class EventType < ApplicationRecord
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        flash[:warning] = 'User updated'
        format.html { redirect_to @event}
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if event_params[:retire].present?
        @event.retire = Time.now
      end

      if @event.update(event_params)
        flash[:success] = 'Event was successfully updated.'

        format.html { redirect_to @event }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :description, :startDate, :distance_id, :startLocation, :visible, :retire_me)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(event) do |f| %>
  <%= error_messages_for(f.object) %>

    <div class="form-group row">
      <%= f.label :title, class: 'col-xs-2 col-form-label'  %>
      <div class="col-xs-10">
        <%= f.text_field :title, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group row">
      <%= f.label :description, class: 'col-xs-2 col-form-label'  %>
      <div class="col-xs-10">
        <%= f.text_area(:description, class: 'form-control', :size => '40x10') %>
      </div>
    </div>

    <div class="form-group row">
      <%= f.label :startDate, class: 'col-xs-2 col-form-label' %>
      <div class="col-xs-10">
        <%= f.datetime_select(:startDate, :order => [:month, :day, :year], ampm: true) %>
      </div>
    </div>

    <div class="form-group row">
      <%= f.label :distance, class: 'col-xs-2 col-form-label' %>
      <div class="col-xs-10">
        <%= collection_select(:event, :distance_id, Distance.all, :id, :distance_string, prompt: true, :include_blank => true) %>
      </div>
    </div>

    <div class="form-group row">
      <%= f.label :startLocation, class: 'col-xs-2 col-form-label'  %>
      <div class="col-xs-10">
        <%= f.text_field :startLocation, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group row">
      <%= f.label :visible, class: 'col-xs-2 col-form-label'  %>
      <div class="col-xs-10">
        <%= f.check_box(:visible) %>
      </div>
    </div>

    <div class="form-group row">
      <%= f.label :retire, class: 'col-xs-2 col-form-label'  %>
      <div class="col-xs-10">
        <%= f.check_box(:retire) %>
      </div>
    </div>

    <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<table class="table" summary="Admin User list" id="table_users">
  <thead>
  <tr class="header">
    <th>id</th>
    <th>title</th>
    <th>description</th>
    <th>start date</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.id %></td>
        <td><%= event.title %></td>
        <td><%= event.description %></td>
        <td><%= event.startDate %></td>
        <td><%= link_to 'Show', event %><br />
        <%= link_to 'Edit', edit_event_path(event) %><br />
        <%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>


<div class="event how">
  <h2>Show Event</h2>

  <table class="table" summary="Event detail view">
    <tr>
      <th>Title: </th>
      <td><%= @event.title %></td>
    </tr>
    <tr>
      <th>description: </th>
      <td><%= @event.description %></td>
    </tr>
    <tr>
      <th>start date: </th>
      <td><%= @event.startDate.to_s(:custom_datetime) %></td>
    </tr>
    <tr>
      <th>distance: </th>
      <td>
        <% if !@event.distance.nil? %>
        <%= @event.distance.distance_string %>
        <% end %>
      </td>
    </tr>
    <tr>
      <th>location: </th>
      <td><%= @event.startLocation %></td>
    </tr>
    <tr>
      <th>visible: </th>
      <td><%= @event.visible %></td>
    </tr>
    <tr>
      <th>retire: </th>
      <td><%= @event.retire %></td>
    </tr>
  </table>
</div>